import Head from 'next/head';
import HomeWrapper from '../src/components/home/HomeWrapper';

export default function Home() {
  return (
    <>
      <Head>
        <title>CryptoCompare - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compare.png" />
      </Head>
      <HomeWrapper/>
    </>
  )
}
